# -*- coding: utf-8 -*-
"""CV_Assignment02_Task01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOKc31jnU3yPq-OrcCEaqBBO3U7H6cDX
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

!pip install opencv-python==3.3.0.10 opencv-contrib-python==3.3.0.10

import cv2

from google.colab import drive
drive.mount('/content/gdrive')

"""# **Task-1 : Image Feature Extraction and Matching**"""

### Reading Images
image1 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/book.jpg')
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

image2 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/book_person_holding.jpg')
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

image3 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/roma_1.jpg')
gray3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)

image4 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/roma_2.jpg')
gray4 = cv2.cvtColor(image4, cv2.COLOR_BGR2GRAY)

image5 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/building_1.jpg')
gray5 = cv2.cvtColor(image5, cv2.COLOR_BGR2GRAY)

image6 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/building_2.jpg')
gray6 = cv2.cvtColor(image6, cv2.COLOR_BGR2GRAY)

image7 = cv2.imread('/content/gdrive/MyDrive/Colab Notebooks/CV_Assignment2/A2_task1_images/building_3.jpg')
gray7 = cv2.cvtColor(image7, cv2.COLOR_BGR2GRAY)

def Set1():
  f, ax = plt.subplots(1, 2, figsize=(9,4)) # no. of rows, images in a row, figure size

  ax[0].imshow(cv2.cvtColor(image1_points,cv2.COLOR_BGR2RGB))
  ax[1].imshow(cv2.cvtColor(image2_points,cv2.COLOR_BGR2RGB))

  ax[0].set_title('Book')
  ax[1].set_title('Person Holding Book')

  plt.tight_layout()
  plt.show()

  len(keypoints_1), len(keypoints_2)
  bf = cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)
  matches = bf.match(descriptors_1, descriptors_2)
  matches = sorted(matches, key= lambda x:x.distance)

  print("Book and Person Holding Book")
  new_image1 = cv2.drawMatches(image1, keypoints_1, image2, keypoints_2, matches[:10], image2, flags=2)
  plt.figure(figsize=(15,10))
  plt.imshow(new_image1)
  plt.show()

def Set2():
  f, ax = plt.subplots(1, 2, figsize=(20,10)) # no. of rows, images in a row, figure size

  ax[0].imshow(cv2.cvtColor(image3_points,cv2.COLOR_BGR2RGB))
  ax[1].imshow(cv2.cvtColor(image4_points,cv2.COLOR_BGR2RGB))

  ax[0].set_title('Roma 1')
  ax[1].set_title('Roma 2')

  plt.tight_layout()
  plt.show()

  len(keypoints_3), len(keypoints_4)
  bf = cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)
  matches = bf.match(descriptors_3, descriptors_4)
  matches = sorted(matches, key= lambda x:x.distance)

  print("Roma_1 and Roma_2")
  new_image2 = cv2.drawMatches(image3, keypoints_3, image4, keypoints_4, matches[:10], image4, flags=2)
  plt.figure(figsize=(15,10))
  plt.imshow(new_image2)
  plt.show()

def Set3():
  f, ax = plt.subplots(1, 3, figsize=(9,4)) # no. of rows, images in a row, figure size

  ax[0].imshow(cv2.cvtColor(image5_points,cv2.COLOR_BGR2RGB))
  ax[1].imshow(cv2.cvtColor(image6_points,cv2.COLOR_BGR2RGB))
  ax[2].imshow(cv2.cvtColor(image7_points,cv2.COLOR_BGR2RGB))

  ax[0].set_title('Building 1')
  ax[1].set_title('Building 2')
  ax[2].set_title('Building 3')

  plt.tight_layout()
  plt.show()

  len(keypoints_5), len(keypoints_6), len(keypoints_7)
  bf = cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)
  matches1 = bf.match(descriptors_5, descriptors_6)
  matches1 = sorted(matches1, key= lambda x:x.distance)
  matches2 = bf.match(descriptors_6, descriptors_7)
  matches2 = sorted(matches2, key= lambda x:x.distance)
  matches3 = bf.match(descriptors_5, descriptors_7)
  matches3 = sorted(matches3, key= lambda x:x.distance)

  print("Building_1 and Building_2")
  new_image3 = cv2.drawMatches(image5, keypoints_5, image6, keypoints_6, matches1[:10], image6, flags=2)
  plt.figure(figsize=(15,10))
  plt.imshow(new_image3)
  plt.show()

  print("Building_2 and Building_3")
  new_image4 = cv2.drawMatches(image6, keypoints_6, image7, keypoints_7, matches2[:10], image7, flags=2)
  plt.figure(figsize=(15,10))
  plt.imshow(new_image4)
  plt.show()

  print("Building_1 and Building_3")
  new_image5 = cv2.drawMatches(image5, keypoints_5, image7, keypoints_7, matches3[:10], image7, flags=2)
  plt.figure(figsize=(15,10))
  plt.imshow(new_image5)
  plt.show()

"""# **1. SIFT**"""

### SIFT
sift = cv2.xfeatures2d.SIFT_create()

### Calculating Keypoints
keypoints_1, descriptors_1 = sift.detectAndCompute(image1, None)
image1_points = cv2.drawKeypoints(gray1, keypoints_1, image1)

keypoints_2, descriptors_2 = sift.detectAndCompute(image2, None)
image2_points = cv2.drawKeypoints(gray2, keypoints_2, image2)

keypoints_3, descriptors_3 = sift.detectAndCompute(image3, None)
image3_points = cv2.drawKeypoints(gray3, keypoints_3, image3)

keypoints_4, descriptors_4 = sift.detectAndCompute(image4, None)
image4_points = cv2.drawKeypoints(gray4, keypoints_4, image4)

keypoints_5, descriptors_5 = sift.detectAndCompute(image5, None)
image5_points = cv2.drawKeypoints(gray5, keypoints_5, image5)

keypoints_6, descriptors_6 = sift.detectAndCompute(image6, None)
image6_points = cv2.drawKeypoints(gray6, keypoints_6, image6)

keypoints_7, descriptors_7 = sift.detectAndCompute(image7, None)
image7_points = cv2.drawKeypoints(gray7, keypoints_7, image7)

Set1()
Set2()
Set3()

"""# **2. ORB**"""

### ORB
orb = cv2.ORB_create()

### Calculating Keypoints
keypoints_1, descriptors_1 = orb.detectAndCompute(image1, None)
image1_points = cv2.drawKeypoints(gray1, keypoints_1, image1)

keypoints_2, descriptors_2 = orb.detectAndCompute(image2, None)
image2_points = cv2.drawKeypoints(gray2, keypoints_2, image2)

keypoints_3, descriptors_3 = orb.detectAndCompute(image3, None)
image3_points = cv2.drawKeypoints(gray3, keypoints_3, image3)

keypoints_4, descriptors_4 = orb.detectAndCompute(image4, None)
image4_points = cv2.drawKeypoints(gray4, keypoints_4, image4)

keypoints_5, descriptors_5 = orb.detectAndCompute(image5, None)
image5_points = cv2.drawKeypoints(gray5, keypoints_5, image5)

keypoints_6, descriptors_6 = orb.detectAndCompute(image6, None)
image6_points = cv2.drawKeypoints(gray6, keypoints_6, image6)

keypoints_7, descriptors_7 = orb.detectAndCompute(image7, None)
image7_points = cv2.drawKeypoints(gray7, keypoints_7, image7)

Set1()
Set2()
Set3()

"""# **3. SURF**"""

### SURF
surf = cv2.xfeatures2d.SURF_create()

### Calculating Keypoints
keypoints_1, descriptors_1 = surf.detectAndCompute(image1, None)
image1_points = cv2.drawKeypoints(gray1, keypoints_1, image1)

keypoints_2, descriptors_2 = surf.detectAndCompute(image2, None)
image2_points = cv2.drawKeypoints(gray2, keypoints_2, image2)

keypoints_3, descriptors_3 = surf.detectAndCompute(image3, None)
image3_points = cv2.drawKeypoints(gray3, keypoints_3, image3)

keypoints_4, descriptors_4 = surf.detectAndCompute(image4, None)
image4_points = cv2.drawKeypoints(gray4, keypoints_4, image4)

keypoints_5, descriptors_5 = surf.detectAndCompute(image5, None)
image5_points = cv2.drawKeypoints(gray5, keypoints_5, image5)

keypoints_6, descriptors_6 = surf.detectAndCompute(image6, None)
image6_points = cv2.drawKeypoints(gray6, keypoints_6, image6)

keypoints_7, descriptors_7 = surf.detectAndCompute(image7, None)
image7_points = cv2.drawKeypoints(gray7, keypoints_7, image7)

Set1()
Set2()
Set3()